/** @type {import("prettier").Config} */
module.exports = {
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
  importOrder: [
    '^react$',
    '<THIRD_PARTY_MODULES>',
    '^@/constants/(.*)$',
    '^@/types/(.*)$',
    '^@/gql/(.*)$',
    '^@/services/(.*)$',
    '^@/utils/(.*)$',
    '^@/lib/(.*)$',
    '^@/context/(.*)$',
    '^@/hooks/(.*)$',
    '^@/svg/(.*)$',
    '^@/screens/(.*)$',
    '^@/layouts/(.*)$',
    '^@/atoms/(.*)$',
    '^@/components/(.*)$',
    '^@/styles/(.*)$',
    '^constants/(.*)$',
    '^types/(.*)$',
    '^gql/(.*)$',
    '^services/(.*)$',
    '^utils/(.*)$',
    '^lib/(.*)$',
    '^context/(.*)$',
    '^hooks/(.*)$',
    '^svg/(.*)$',
    '^screens/(.*)$',
    '^layouts/(.*)$',
    '^atoms/(.*)$',
    '^components/(.*)$',
    '^styles/(.*)$',
    '^./(.*)$',
    '^[./]',
    '^[../]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
};
